### ISSUE TITLE
Could not find the backend to open with iomode "ri"

### ISSUE THREAD

**Issue by Mnl-GRTN** [Aeonss/BubbleBlaster#1]
The error is : 

`Traceback (most recent call last):
  File "C:\Users\33682\Desktop\AI\bubbleblaster.py", line 128, in <module>
    OCR()
  File "C:\Users\33682\Desktop\AI\bubbleblaster.py", line 44, in OCR
    result = reader.readtext(IMAGE)
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\easyocr\easyocr.py", line 442, in readtext
    img, img_cv_grey = reformat_input(image)
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\easyocr\utils.py", line 699, in reformat_input
    img = loadImage(image)  # can accept URL
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\easyocr\imgproc.py", line 12, in loadImage
    img = io.imread(img_file)           # RGB order
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\skimage\io\_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\skimage\io\manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\skimage\io\_plugins\imageio_plugin.py", line 15, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\imageio\v2.py", line 226, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "C:\Users\33682\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\imageio\core\imopen.py", line 298, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `test.jpg`` with iomode `ri`.`

Is there anything I can do to make this work ?

**Comment by Aeonss** [comment]
Hmm, I'm not sure about this error. Have this worked before with other images? And can you send the image so I can test it out for myself?

**Comment by Mnl-GRTN** [comment]
It never worked, I just took a random image which is this one: 
![test](https://user-images.githubusercontent.com/51137532/212468752-f885555e-20e6-41be-bf6a-2d6eb59cc91d.jpg)

Update : I tried with some other images and it worked, Does this have anything to do with the image format?

**Comment by Aeonss** [comment]
Yes, I do believe so. I've tested some jpgs and pngs but for some reason the jpg that you have send me doesn't work. I've pushed an update which gives the "--png" flag (where you can just add to the end of the command" to auto convert the jpg to png. E.g.    python bubbleblaster.py -i a.jpg --png)

For example, if you're trying to OCR a.jpg, the program will create a "a_png.png", which will then create a "a_png_ocr.png", which is the result that you want. Here's the result images.

![a](https://user-images.githubusercontent.com/30298077/212492622-5c84348a-0034-4c5d-9f20-189b7b07d1a0.jpg)
![a_png](https://user-images.githubusercontent.com/30298077/212492623-4120bd3a-58da-41bc-8afb-72ba3fc4c273.png)
![a_png_ocr](https://user-images.githubusercontent.com/30298077/212492624-3d9c0380-98f8-431d-a5fa-9c6d7a17edbc.png)

You'll have to redownload the initial python file again, and possible run "pip install -r requirements.txt" since it uses the PILLOW python library.

I'm not sure why this specific jpg doesn't work, probably something to do with the OCR library where it can't open the jpg file. Let me know if you have anymore issues, otherwise I'll close this issue after a couple days.
