### ISSUE TITLE
Error when starting app

### ISSUE THREAD

**Issue by CroSSer23** [Aeonss/BubbleBlaster#11]
Something wrong can you help me?
Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\NIK\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\NIK\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\NIK\Downloads\BubbleBlaster\bubbleblaster.py", line 155, in blast
    result = reader.readtext(image)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NIK\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyocr\easyocr.py", line 464, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NIK\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyocr\easyocr.py", line 383, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NIK\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyocr\utils.py", line 613, in get_image_list
    crop_img,ratio = compute_ratio_and_resize(crop_img,width,height,model_height)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NIK\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyocr\utils.py", line 576, in compute_ratio_and_resize
    img = cv2.resize(img,(int(model_height*ratio),model_height),interpolation=Image.ANTIALIAS)
                                                                              ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by Aeonss** [comment]
Try the latest release
