### ISSUE TITLE
Bat file does not open

### ISSUE THREAD

**Issue by taf1kkk** [Aeonss/BubbleBlaster#13]
I installed all the dependencies but when I try to open the bat file it starts for a second and disappears

**Comment by taf1kkk** [comment]
Traceback (most recent call last):
  File "bubbleblaster.py", line 14, in <module>
    import easyocr
  File "C:\Users\layme\AppData\Local\Programs\Python\Python37\lib\site-packages\easyocr\__init__.py", line 1, in <module>
    from .easyocr import Reader
  File "C:\Users\layme\AppData\Local\Programs\Python\Python37\lib\site-packages\easyocr\easyocr.py", line 3, in <module>
    from .recognition import get_recognizer, get_text
  File "C:\Users\layme\AppData\Local\Programs\Python\Python37\lib\site-packages\easyocr\recognition.py", line 6, in <module>
    import torchvision.transforms as transforms
  File "C:\Users\layme\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "C:\Users\layme\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\models\__init__.py", line 16, in <module>
    from .maxvit import *
  File "C:\Users\layme\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\models\maxvit.py", line 3, in <module>
    from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
ImportError: cannot import name 'OrderedDict' from 'typing' (C:\Users\layme\AppData\Local\Programs\Python\Python37\lib\typing.py)

**Comment by Aeonss** [comment]
Try the latest release
