### ISSUE TITLE
ok....... I am again

### ISSUE THREAD

**Issue by jxhxgt** [Aeonss/BubbleBlaster#17]
PS E:\BubbleBlaster> python bubbleblaster.py
Traceback (most recent call last):
  File "E:\BubbleBlaster\bubbleblaster.py", line 281, in <module>
    app = App()
  File "E:\BubbleBlaster\bubbleblaster.py", line 31, in __init__
    self.checkUpdate()
  File "E:\BubbleBlaster\bubbleblaster.py", line 274, in checkUpdate
    if latest_tag > self.tag:
TypeError: '>' not supported between instances of 'NoneType' and 'str'
PS E:\BubbleBlaster>

**Comment by Aeonss** [comment]
Hmm, I couldn't replicate the problem, but I assume its because you might have been trying to use it while it was offline and it couldn't get the latest tag of the newest release. I've updated the code so it ignores this problem. Try version 1.2.2

**Comment by jxhxgt** [comment]
nice
