### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NyxBenders** [Aeonss/BubbleBlaster#37]
PS C:\Users\Ryan\Desktop\clean\bubble ia> & C:/Users/Ryan/AppData/Local/Programs/Python/Python311/python.exe "c:/Users/Ryan/Desktop/clean/bubble ia/bubbleblaster.py"
Traceback (most recent call last):
  File "c:\Users\Ryan\Desktop\clean\bubble ia\bubbleblaster.py", line 14, in <module>
    import util
  File "c:\Users\Ryan\Desktop\clean\bubble ia\util.py", line 3, in <module>
    import torch
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\__init__.py", line 148, in <module>       
    raise err
OSError: [WinError 126] Não foi possível encontrar o módulo especificado. Error loading "C:\Users\Ryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

![image](https://github.com/user-attachments/assets/1f3e9760-cfd7-4a5c-b065-14e00c1118ed)

**Comment by Aeonss** [comment]
I reuploaded the BubbleBlaster 2.0.2 and fixed the duplicate numpy error in requirements.txt. Try downloading and reinstalling the dependencies again

**Comment by NyxBenders** [comment]
Thank you, but now when I open the .exe or .bat file, the CMD window appears and then it closes by itself. The program doesn't open.

**Comment by geocotne** [comment]
Same

**Comment by geocotne** [comment]
Its The Same Error i Checked it

**Comment by DearFox** [comment]
to see errors - add `PAUSE` to a new line at the very end of your .bat

And yes, I get it too:
`Error loading "C:\Users\UserName\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies. `

**Comment by DearFox** [comment]
exe version has the same error. True, the path to fbgemm.dll is different

**Comment by AerialAtom** [comment]
https://stackoverflow.com/questions/78114412/import-torch-how-to-fix-oserror-winerror-126-error-loading-fbgemm-dll-or-depen

The issue solved by simply downloading [libomp140.x86_64.dll](https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download) and place it in 'C:\Windows\System32'

**Comment by DearFox** [comment]
> https://stackoverflow.com/questions/78114412/import-torch-how-to-fix-oserror-winerror-126-error-loading-fbgemm-dll-or-depen
> 
> The issue solved by simply downloading [libomp140.x86_64.dll](https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download) and place it in 'C:\Windows\System32'

Looks like a very strange solution to the problem. Besides, I don’t trust this site.
I hope the program developer will fix the error without having to download strange files from strange sites.
