### ISSUE TITLE
_tkinter.TclError: unknown color name "transparent"

### ISSUE THREAD

**Issue by Niptlox** [Aeonss/BubbleBlaster#4]
Traceback (most recent call last):
  File "D:\PythonProjects\MangoEditer\BubbleBlaster\bubbleblaster.py", line 265, in <module>
    app = App()
  File "D:\PythonProjects\MangoEditer\BubbleBlaster\bubbleblaster.py", line 39, in __init__
    self.inputFrame = ctk.CTkFrame(self, width=500, fg_color="transparent")
  File "D:\PythonProjects\MangoEditer\venv\lib\site-packages\customtkinter\widgets\ctk_frame.py", line 52, in __init__
    self.draw()
  File "D:\PythonProjects\MangoEditer\venv\lib\site-packages\customtkinter\widgets\ctk_frame.py", line 92, in draw
    self.canvas.itemconfig("inner_parts",
  File "D:\PythonProjects\MangoEditer\venv\lib\site-packages\customtkinter\widgets\ctk_canvas.py", line 94, in itemconfig
    super().itemconfigure(configure_id, *args, **kwargs_except_outline)
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 2898, in itemconfigure
    return self._configure(('itemconfigure', tagOrId), cnf, kw)
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown color name "transparent"

**Comment by Aeonss** [comment]
Yeah you'll have to do

pip uninstall customtkinter
pip install customtkinter

Because of an outdated customtkinter verison, thanks for the pull request
