### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Kellenok** [Aeonss/BubbleBlaster#6]
```
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Downloading recognition model, please wait. This may take several minutes depending upon your network connection.
Progress: |██████████████████████████████████████████████████| 100.1% CompleteException in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "D:\загрузки\BubbleBlaster\bubbleblaster.py", line 140, in blast
    result = reader.readtext(image)
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\easyocr.py", line 456, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\easyocr.py", line 379, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\utils.py", line 540, in get_image_list
    maximum_y,maximum_x = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by Aeonss** [comment]
> ```
> CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
> Downloading recognition model, please wait. This may take several minutes depending upon your network connection.
> Progress: |██████████████████████████████████████████████████| 100.1% CompleteException in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
>     return self.func(*args)
>   File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
>     self._command()
>   File "D:\загрузки\BubbleBlaster\bubbleblaster.py", line 140, in blast
>     result = reader.readtext(image)
>   File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\easyocr.py", line 456, in readtext
>     result = self.recognize(img_cv_grey, horizontal_list, free_list,\
>   File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\easyocr.py", line 379, in recognize
>     image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
>   File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\utils.py", line 540, in get_image_list
>     maximum_y,maximum_x = img.shape
> AttributeError: 'NoneType' object has no attribute 'shape'
> ```

Can you give me the image you tried to use?

**Comment by apt42541** [comment]
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Apt_S\Downloads\BubbleBlaster\bubbleblaster.py", line 140, in blast
    result = reader.readtext(image)
  File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 456, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
  File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 379, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\utils.py", line 540, in get_image_list
    maximum_y,maximum_x = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
![07](https://user-images.githubusercontent.com/12625408/234797129-18145d2d-3eb3-4715-b926-8bd76bce5fc3.jpg)

**Comment by Aeonss** [comment]
Hmm, this is weird, I'm

> CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU. Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\tkinter__init__.py", line 1921, in **call** return self.func(*args) File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked self._command() File "C:\Users\Apt_S\Downloads\BubbleBlaster\bubbleblaster.py", line 140, in blast result = reader.readtext(image) File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 456, in readtext result = self.recognize(img_cv_grey, horizontal_list, free_list, File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 379, in recognize image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH) File "C:\Users\Apt_S\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\utils.py", line 540, in get_image_list maximum_y,maximum_x = img.shape AttributeError: 'NoneType' object has no attribute 'shape' ![07](https://user-images.githubusercontent.com/12625408/234797129-18145d2d-3eb3-4715-b926-8bd76bce5fc3.jpg)

Hmm, this is weird, I'm not getting the same error.

Try doing 
`pip uninstall easyocr`
and then doing
`pip install easyocr`

**Comment by apt42541** [comment]
tried but not work

**Comment by Aeonss** [comment]
> tried but not work

Might be a dependency issue, let me update my modules and see if anything breaks and I'll get back to you

**Comment by Aeonss** [comment]
> 

I updated the requirements.txt, download the new zip file from https://github.com/Aeonss/BubbleBlaster/releases/tag/1.1 called "BubbleBlaster_v1.1_alpha" and try doing `pip install -r requirements.txt` again. Let me know if it doesn't work for you.

**Comment by Aeonss** [comment]
> tried but not work

I updated the requirements.txt, download the new zip file from https://github.com/Aeonss/BubbleBlaster/releases/tag/1.1 called "BubbleBlaster_v1.1_alpha" and try doing `pip install -r requirements.txt` again. Let me know if it doesn't work for you.

**Comment by apt42541** [comment]
![image](https://user-images.githubusercontent.com/12625408/234890269-5f1e6647-f00d-4e6a-b92e-a3f2ea207925.png)

**Comment by Aeonss** [comment]
> ![image](https://user-images.githubusercontent.com/12625408/234890269-5f1e6647-f00d-4e6a-b92e-a3f2ea207925.png)

Ok I lowered the compatibility for opencv_python_headless in requirements.txt, try again with the new release BubbleBlaster1.1_beta.zip in the releases

**Comment by Aeonss** [comment]
EDIT: This is it, I'm able to replicate the error, working on a fix now.

https://github.com/JaidedAI/EasyOCR/issues/629

**Comment by Aeonss** [comment]
Fixed in version 1.2, found [here](https://github.com/Aeonss/BubbleBlaster/releases/tag/1.2)

Let me know if its solved, and I'll close this issue

**Comment by Kellenok** [comment]
use image by [apt42541](https://github.com/apt42541) i get new error:
Traceback (most recent call last):
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "D:\BubbleBlaster.v1.2\bubbleblaster.py", line 155, in blast
    result = reader.readtext(image)
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\easyocr.py", line 456, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\easyocr.py", line 379, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "C:\Users\gleb1\AppData\Local\Programs\Python\Python39\lib\site-packages\easyocr\utils.py", line 540, in get_image_list
    maximum_y,maximum_x = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Kellenok** [comment]
so, i realized the problem was that the address of the picture had russian letters. english and korean cleans almost perfectly, but japanese work badly. but thx for app
![image](https://user-images.githubusercontent.com/76692731/235122238-da65a351-ab2e-4988-b328-ff2852ba647a.png)
![image](https://user-images.githubusercontent.com/76692731/235122430-b8b6a1ea-01ad-4aa9-9bea-cca99a7ba6ac.png)
![image](https://user-images.githubusercontent.com/76692731/235122512-d2b52329-383b-4702-be18-abfdd73f7f43.png)

**Comment by 182524** [comment]
-819200.0% Complete[ WARN:0@2.447] global loadsave.cpp:241 cv::findDecoder imread_('C:\Users\鐜嬪竻\AppData\Local\Temp\tmp54jta4mf'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\kail\EasyOCR\easy.py", line 4, in <module>
    result = reader.readtext('http://127.0.0.1/yanzheng/yanzhengma.php')
  File "C:\Program Files\Python39\lib\site-packages\easyocr\easyocr.py", line 468, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
  File "C:\Program Files\Python39\lib\site-packages\easyocr\easyocr.py", line 383, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "C:\Program Files\Python39\lib\site-packages\easyocr\utils.py", line 583, in get_image_list
    maximum_y,maximum_x = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
